---
# tasks file for vector-role
    - name: Get vector distrib
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.{{ vector_arch }}.rpm"
        dest: "./vector-{{ vector_version }}.rpm"
      tags:
        - distrib
        - vector
    - name: Install Vector
      become: true
      ansible.builtin.yum:
        name:
          - ./vector-{{ vector_version }}.rpm